{"name": "test_get_deal_link", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '..\\\\log\\\\站群.txt'", "trace": "self = <test_case.test_found.Testfound object at 0x000001DA9A578F20>\n\n    def test_get_deal_link(self):\n    \n        log_file_path = r'..\\log\\站群.txt'\n        store_detail = TemuFound()\n    \n        try:\n            get_deal_found = store_detail.link_ele()\n            print(get_deal_found)\n>           assert get_deal_found == link_found, f\"WA0262-found get deal的affi-Link链接错误\"   #  get deal的affi-Link断言\nE           AssertionError: WA0262-found get deal的affi-Link链接错误\nE           assert '' == 'https://temu...m/u2rh64mil0s'\nE             \nE             - https://temu.to/m/u2rh64mil0s\n\ntest_case\\test_found.py:35: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_case.test_found.Testfound object at 0x000001DA9A578F20>\n\n    def test_get_deal_link(self):\n    \n        log_file_path = r'..\\log\\站群.txt'\n        store_detail = TemuFound()\n    \n        try:\n            get_deal_found = store_detail.link_ele()\n            print(get_deal_found)\n            assert get_deal_found == link_found, f\"WA0262-found get deal的affi-Link链接错误\"   #  get deal的affi-Link断言\n    \n        except AssertionError as AE:\n            error_log = str(AE)\n>           log_error(log_file_path, error_log)\n\ntest_case\\test_found.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfile = '..\\\\log\\\\站群.txt', info = \"WA0262-found get deal的affi-Link链接错误\\nassert '' == 'https://temu...m/u2rh64mil0s'\\n  \\n  - https://temu.to/m/u2rh64mil0s\"\n\n    def log_error(file,info):\n        current_time = time.strftime('%Y-%m-%d %H:%M:%S')\n        error_info = current_time+ ' ' + info   #字符串拼接\n        #生成一个txt文件\n>       with open(file, 'a', encoding= 'utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '..\\\\log\\\\站群.txt'\n\nlog\\get_log.py:14: FileNotFoundError"}, "start": 1712903431503, "stop": 1712903436150, "uuid": "db38ba2d-e410-4394-bd4f-b377daa63519", "historyId": "a65351daf241ecbcefdc45307705cb3b", "testCaseId": "a65351daf241ecbcefdc45307705cb3b", "fullName": "test_case.test_found.Testfound#test_get_deal_link", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_found"}, {"name": "subSuite", "value": "Testfound"}, {"name": "host", "value": "DESKTOP-LPVFBLF"}, {"name": "thread", "value": "16788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_found"}]}